import type { Child, FC } from 'hono/jsx';
// Tailwind-built stylesheet, imported as raw text via the wrangler Text rule
// (see wrangler.jsonc) and inlined below. Generated by `pnpm build:css`.
// eslint-disable-next-line import/default
import CSS from '@/styles/app.css';

export const Layout: FC<{ title: string; base: string; children?: Child }> = (
    props,
) => (
    <html lang="en">
        <head>
            <meta charset="utf-8" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <title>{props.title}</title>
            <meta
                name="description"
                content="TokenTally — a public leaderboard of tokens burned by AI builders on Claude Code and Codex."
            />
            {/* eslint-disable-next-line */}
            <style dangerouslySetInnerHTML={{ __html: CSS }} />
        </head>
        <body>
            <div class="mx-auto max-w-[960px] px-5 pt-6 pb-16">
                <header class="mb-7 flex flex-wrap items-center justify-between gap-4 border-b border-border py-4">
                    <a
                        class="text-xl font-extrabold tracking-[-0.02em] text-text"
                        href="/"
                    >
                        Token<span class="text-accent">Tally</span>
                    </a>
                    <nav>
                        <a
                            class="ml-[18px] font-medium text-muted hover:text-text"
                            href="/"
                        >
                            Leaderboard
                        </a>
                        <a
                            class="ml-[18px] font-medium text-muted hover:text-text"
                            href="/start"
                        >
                            Get started
                        </a>
                        <a
                            class="ml-[18px] font-medium text-muted hover:text-text"
                            href="/about"
                        >
                            About
                        </a>
                    </nav>
                </header>
                {props.children}
                <footer class="mt-12 border-t border-border pt-5 text-[13px] text-muted">
                    <p>
                        TokenTally · self-reported, honor-system token counts
                        from Claude Code &amp; Codex · no PII stored ·{' '}
                        <a href="/about">how it works</a>
                    </p>
                </footer>
            </div>
        </body>
    </html>
);
