import type { Child, FC } from 'hono/jsx';
import { Button } from '@/pages/components/button';
// Tailwind-built stylesheet, imported as raw text via the wrangler Text rule
// (see wrangler.jsonc) and inlined below. Generated by `pnpm build:css`.
// eslint-disable-next-line import/default
import CSS from '../styles/app.css';

function Mark(props: { class?: string }): ReturnType<FC<{ class?: string }>> {
    return (
        <svg
            class={props.class ?? 'h-7 w-7'}
            viewBox="0 0 100 100"
            fill="none"
            aria-hidden="true"
        >
            <g fill="currentColor">
                <rect
                    x="22"
                    y="68"
                    width="36"
                    height="12"
                    rx="6"
                    opacity="0.4"
                />
                <rect
                    x="32"
                    y="48"
                    width="36"
                    height="12"
                    rx="6"
                    opacity="0.7"
                />
                <rect
                    x="42"
                    y="28"
                    width="36"
                    height="12"
                    rx="6"
                />
            </g>
        </svg>
    );
}

function Wordmark(props: {
    class?: string;
}): ReturnType<FC<{ class?: string }>> {
    return (
        <span
            class={`wm font-display font-medium tracking-[-0.05em] ${props.class ?? ''}`}
        >
            token<span class="max">maxer</span>
            <span class="tld">.quest</span>
        </span>
    );
}

const SITE_DESCRIPTION =
    'tokenmaxer.quest — a public leaderboard of tokens burned by AI builders on Claude Code, Codex, opencode and pi.';

export const Layout: FC<{ title: string; base: string; children?: Child }> = (
    props,
) => {
    const origin = props.base.replace(/\/$/u, '');
    const ogImage = `${origin}/og.png`;
    return (
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <title>{props.title}</title>
                <meta
                    name="description"
                    content={SITE_DESCRIPTION}
                />
                <meta
                    name="theme-color"
                    content="#0a0a0a"
                />
                <link
                    rel="icon"
                    href="/favicon.svg"
                    type="image/svg+xml"
                />
                <link
                    rel="icon"
                    href="/favicon-32x32.png"
                    type="image/png"
                    sizes="32x32"
                />
                <link
                    rel="icon"
                    href="/favicon-16x16.png"
                    type="image/png"
                    sizes="16x16"
                />
                <link
                    rel="apple-touch-icon"
                    href="/apple-touch-icon.png"
                    sizes="180x180"
                />
                <link
                    rel="manifest"
                    href="/site.webmanifest"
                />
                <meta
                    property="og:type"
                    content="website"
                />
                <meta
                    property="og:site_name"
                    content="tokenmaxer.quest"
                />
                <meta
                    property="og:title"
                    content={props.title}
                />
                <meta
                    property="og:description"
                    content={SITE_DESCRIPTION}
                />
                <meta
                    property="og:url"
                    content={origin}
                />
                <meta
                    property="og:image"
                    content={ogImage}
                />
                <meta
                    property="og:image:width"
                    content="1200"
                />
                <meta
                    property="og:image:height"
                    content="630"
                />
                <meta
                    property="og:image:alt"
                    content="tokenmaxer.quest — token leaderboard for AI builders"
                />
                <meta
                    name="twitter:card"
                    content="summary_large_image"
                />
                <meta
                    name="twitter:title"
                    content={props.title}
                />
                <meta
                    name="twitter:description"
                    content={SITE_DESCRIPTION}
                />
                <meta
                    name="twitter:image"
                    content={ogImage}
                />
                <link
                    rel="preconnect"
                    href="https://fonts.googleapis.com"
                />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossorigin="anonymous"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Mona+Sans:wght@500;600;700;800;900&family=Inter:opsz,wght@14..32,400;14..32,500&display=swap"
                    rel="stylesheet"
                />
                {/* eslint-disable-next-line */}
                <style dangerouslySetInnerHTML={{ __html: CSS }} />
            </head>
            <body>
                <a
                    class="skip-link"
                    href="#main"
                >
                    Skip to content
                </a>
                <div class="mx-auto max-w-[1199px] px-5 pb-20 sm:px-8">
                    <header class="sticky top-0 z-50 -mx-5 mb-2 flex flex-wrap items-center justify-between gap-x-6 gap-y-3 border-b border-border bg-canvas/95 px-5 py-3.5 backdrop-blur-sm sm:-mx-8 sm:px-8">
                        <a
                            class="nav-link flex items-center gap-2.5 text-text no-underline hover:no-underline"
                            href="/"
                        >
                            <Mark />
                            <Wordmark class="text-sm tracking-[-0.02em] sm:text-[15px]" />
                        </a>
                        <nav class="order-3 flex w-full flex-wrap items-center gap-x-6 gap-y-2 text-[14px] font-medium text-muted sm:order-none sm:w-auto sm:justify-center">
                            <a
                                class="nav-link text-muted no-underline hover:text-text hover:no-underline"
                                href="/"
                            >
                                Leaderboard
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text hover:no-underline"
                                href="/start"
                            >
                                Get started
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text hover:no-underline"
                                href="/about"
                            >
                                About
                            </a>
                        </nav>
                        <Button
                            variant="primary"
                            href="/start"
                        >
                            Get started
                        </Button>
                    </header>

                    <main id="main">{props.children}</main>

                    <footer class="mt-24 grid gap-10 border-t border-border pt-12 text-[13px] text-muted md:grid-cols-[1.4fr_1fr_1fr]">
                        <div>
                            <a
                                class="nav-link mb-4 flex items-center gap-2.5 text-text no-underline hover:no-underline"
                                href="/"
                            >
                                <Mark class="h-6 w-6" />
                                <Wordmark class="text-sm" />
                            </a>
                            <p class="max-w-[36ch] leading-snug">
                                Self-reported, honor-system token counts from
                                Claude Code, Codex, opencode &amp; pi. No
                                prompts, no PII.
                            </p>
                        </div>
                        <div class="flex flex-col gap-2.5">
                            <span class="mb-1 font-display text-[13px] font-semibold tracking-[-0.13px] text-text">
                                Product
                            </span>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/"
                            >
                                Leaderboard
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/start"
                            >
                                Get started
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/about"
                            >
                                About
                            </a>
                        </div>
                        <div class="flex flex-col gap-2.5">
                            <span class="mb-1 font-display text-[13px] font-semibold tracking-[-0.13px] text-text">
                                How it works
                            </span>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/about"
                            >
                                Privacy &amp; honor system
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/start"
                            >
                                Install hooks
                            </a>
                        </div>
                    </footer>
                </div>
            </body>
        </html>
    );
};
