// The Tailwind-built stylesheet is imported as raw text via the wrangler "Text"
// rule and inlined into a <style> tag by the Layout. Generated by `pnpm build:css`.
declare module '*.css' {
    const content: string;
    export default content;
}
